### ISSUE TITLE
view_strikes.php

### ISSUE THREAD

**Issue by mglktech** [pilotvollmar/DTCC-Dashboard#49]
Make view_strikes.php?steamid=$steam_id

Strikes to be listed in a table, showing reason for each.

can be included in view_strikes modal on view_player.php

**Comment by pilotvollmar** [comment]
commit id ac5359cefda68dd182dd122c227c6e38a593152e implements this

**Comment by mglktech** [comment]
ac5359cefda68dd182dd122c227c6e38a593152e implements this
